package org.zstack.header.candidate;

public interface CandidateReasonCodes {
    String HOST_STATE_NOT_ENABLED = "HOST_STATE_NOT_ENABLED";
    String HOST_STATUS_NOT_CONNECTED = "HOST_STATUS_NOT_CONNECTED";
    String HOST_HYPERVISOR_TYPE_NOT_MATCHED = "HOST_HYPERVISOR_TYPE_NOT_MATCHED";
    String HOST_CPU_NOT_ENOUGH = "HOST_CPU_NOT_ENOUGH";
    String HOST_MEMORY_NOT_ENOUGH = "HOST_MEMORY_NOT_ENOUGH";
    String HOST_RESERVED_CAPACITY_NOT_ENOUGH = "HOST_RESERVED_CAPACITY_NOT_ENOUGH";
    String HOST_PRIMARY_STORAGE_REQUIREMENT_NOT_SATISFIED = "HOST_PRIMARY_STORAGE_REQUIREMENT_NOT_SATISFIED";
    String HOST_IN_AVOID_LIST = "HOST_IN_AVOID_LIST";
    String HOST_REJECTED_BY_EXTENSION = "HOST_REJECTED_BY_EXTENSION";
    String HOST_REJECTED_BY_ALLOCATOR_FLOW = "HOST_REJECTED_BY_ALLOCATOR_FLOW";
    String HOST_SKIPPED_BY_PREVIOUS_DECISION = "HOST_SKIPPED_BY_PREVIOUS_DECISION";
    String HOST_REJECTED_BY_ALLOCATOR = "HOST_REJECTED_BY_ALLOCATOR";
    String GPU_DEVICE_STATUS_NOT_AVAILABLE = "GPU_DEVICE_STATUS_NOT_AVAILABLE";
    String GPU_DEVICE_ALREADY_ATTACHED = "GPU_DEVICE_ALREADY_ATTACHED";
    String GPU_DEVICE_TYPE_NOT_MATCHED = "GPU_DEVICE_TYPE_NOT_MATCHED";
    String GPU_SPEC_NOT_MATCHED = "GPU_SPEC_NOT_MATCHED";
    String GPU_SPEC_CAPACITY_NOT_ENOUGH = "GPU_SPEC_CAPACITY_NOT_ENOUGH";
    String PCI_DEVICE_STATUS_NOT_AVAILABLE = "PCI_DEVICE_STATUS_NOT_AVAILABLE";
    String PCI_SPEC_NOT_MATCHED = "PCI_SPEC_NOT_MATCHED";
    String MDEV_DEVICE_STATUS_NOT_AVAILABLE = "MDEV_DEVICE_STATUS_NOT_AVAILABLE";
    String MDEV_SPEC_NOT_MATCHED = "MDEV_SPEC_NOT_MATCHED";
}
